apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-app
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/sidhishruti22/ocm-app
  version:
    semver: v1.0.3-dev
  repository:
    url: ghcr.io/sidhishruti22/ocm-repo
    secretRef:
      name: oci-creds
  verify: []
  references:
    expand: true
